# Project-wide Gradle settings.
# Set JDK for Gradle execution
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17.0.11


# Memory Allocation for Gradle Daemon & Dexing (Prevents OutOfMemory / GC Thrashing)
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -XX:+UseG1GC

# AndroidX & Jetpack Compose options
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.parallel=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
